title: Interview Questions
description: Interview questions for different programming langugaes & technologies
theme: minima # jekyll-theme-leap-day ( except minima, remaing all should be prefixed with jekyll-theme- )
show_downloads: false
